### PR TITLE
header design & burger menu

### PR DESCRIPTION
**Pull request by hebaali9**
I completed the header, if you have any comment fell free to add

### CODE REVIEW

**Review by motazhaj — COMMENTED** [review]
1. What are the ".DS_Store" files that are in every folder?
2. Also for some reason there are edits to the package-lock.json

**Comment by hebaali9** [comment]
1. ".DS_Store"  locally does not appear but I google it and it is sth that  created by macOS Finder i can hide it in gitignore
2. I told the group in our last session that the project did not work so I updated the npm 
3. This is the pic


Screenshot 2024-04-08 at 10 54 47 PM
Screenshot 2024-04-08 at 10 55 10 PM
Screenshot 2024-04-08 at 10 55 48 PM

**Comment by motazhaj** [comment]
This looks great, nice job, so now we just need to find a way to not have conflicts between mac and windows merges

**Comment by hebaali9** [comment]
Thank you Motaz I will do a little search and you can if you would like and we will see

**Pull request closed without merging**
