### PR TITLE
Finishing my cart page

### PR DESCRIPTION
**Pull request by hebaali9**
Finishing my cart page
-It is not perfect thought but I'll enhance it if we got extra time 
- notice that I made an adjustment on App.js "added my cart routing"

### CODE REVIEW

**Review by MohamedAlQadeery — COMMENTED** [review]
Greate work Heba ,but could you move the MuCartButtons to components/shared folder ? because in pages folder we only have our pages container there
image

**Comment by hebaali9** [comment]
Good point Mohamed, I moved it to the Invoice folder since the buttons for it, it's better

**Comment by motazhaj** [comment]
Nice work!

**Review by motazhaj — APPROVED** [review]

**Comment by MohamedAlQadeery** [comment]
Great Work Heba

**Pull request merged**
